import { useState, useEffect, useMemo } from 'react';
import api from '../../services/api';
import Card from '../../components/ui/Card';
import Spinner from '../../components/ui/Spinner';
import { Download, Filter, X, Printer } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export default function VehicleHistory() {
  const { user } = useAuth();
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);

  // Filters
  const [empFilter, setEmpFilter] = useState('');
  const [typeFilter, setTypeFilter] = useState('');
  const [vehicleFilter, setVehicleFilter] = useState('');
  const [driverFilter, setDriverFilter] = useState('');
  const [pickupFrom, setPickupFrom] = useState('');
  const [pickupTo, setPickupTo] = useState('');
  const [sortOrder, setSortOrder] = useState('desc');

  useEffect(() => {
    fetchHistory();
  }, []);

  async function fetchHistory() {
    try {
      const { data } = await api.get('/garage/history');
      setHistory(data.history);
    } catch (err) {
      console.error('Failed to fetch history:', err);
    } finally {
      setLoading(false);
    }
  }

  // Derived unique values for filter dropdowns
  const uniqueVehicles = useMemo(() =>
    [...new Set(history.map(t => t.registration_no).filter(Boolean))].sort(),
    [history]
  );
  const uniqueDrivers = useMemo(() =>
    [...new Set(history.map(t => t.assigned_driver).filter(Boolean))].sort(),
    [history]
  );

  // Apply filters client-side
  const filtered = useMemo(() => {
    return history.filter(trip => {
      if (empFilter && !(trip.employee_number || '').toLowerCase().includes(empFilter.toLowerCase())) return false;
      if (typeFilter && trip.travel_type !== typeFilter) return false;
      if (vehicleFilter && trip.registration_no !== vehicleFilter) return false;
      if (driverFilter && trip.assigned_driver !== driverFilter) return false;
      if (pickupFrom && trip.pickup_time) {
        if (new Date(trip.pickup_time) < new Date(pickupFrom)) return false;
      }
      if (pickupTo && trip.pickup_time) {
        // include full end day
        if (new Date(trip.pickup_time) > new Date(new Date(pickupTo).setHours(23, 59, 59, 999))) return false;
      }
      return true;
    });
  }, [history, empFilter, typeFilter, vehicleFilter, driverFilter, pickupFrom, pickupTo]);

  const sorted = useMemo(() => {
    return [...filtered].sort((a, b) => {
      const dateA = new Date(a.pickup_time || a.travel_date || a.created_at);
      const dateB = new Date(b.pickup_time || b.travel_date || b.created_at);
      return sortOrder === 'desc' ? dateB - dateA : dateA - dateB;
    });
  }, [filtered, sortOrder]);

  const hasFilters = empFilter || typeFilter || vehicleFilter || driverFilter || pickupFrom || pickupTo;

  const clearFilters = () => {
    setEmpFilter('');
    setTypeFilter('');
    setVehicleFilter('');
    setDriverFilter('');
    setPickupFrom('');
    setPickupTo('');
  };

  const exportToExcel = async () => {
    if (sorted.length === 0) return;

    const escape = (val) => {
      if (val == null) return '';
      const str = String(val);
      return (str.includes(',') || str.includes('"') || str.includes('\n'))
        ? '"' + str.replace(/"/g, '""') + '"'
        : str;
    };

    const headers = [
      'Employee', 'Employee No.', 'Department', 'Travel Type',
      'Pickup Location', 'Destination',
      'Vehicle', 'Driver',
      'Pickup Time', 'Travel Date', 'Drop-off Time'
    ];

    const rows = sorted.map(trip => [
      trip.requester_name,
      trip.employee_number,
      trip.department_name,
      trip.travel_type,
      trip.pickup_location,
      trip.destination,
      `${trip.registration_no} (${trip.vehicle_make} ${trip.vehicle_model})`,
      trip.assigned_driver,
      trip.pickup_time ? new Date(trip.pickup_time).toLocaleString('en-IN') : '',
      trip.travel_date,
      trip.dropoff_time ? new Date(trip.dropoff_time).toLocaleString('en-IN') : ''
    ].map(escape));

    const BOM = '\uFEFF';
    const csv = BOM + [headers.join(','), ...rows.map(r => r.join(','))].join('\r\n');

    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'Vehicle_History.csv';
    link.click();
    window.URL.revokeObjectURL(url);
  };

  if (loading) return <Spinner size="lg" className="py-20" />;

  return (
    <div className="space-y-5 animate-fade-in">
      {/* Printable Report Header */}
      <div className="print-header">
        <h1 className="text-xl font-bold">Vehicle Requisition History Report</h1>
        <p className="text-sm">Generated by: {user?.full_name} ({user?.email})</p>
        <p className="text-xs text-slate-500">
          Generated on: {new Date().toLocaleString('en-IN')} 
          {empFilter ? ` | Employee No: ${empFilter}` : ''}
          {typeFilter ? ` | Travel Type: ${typeFilter}` : ''}
          {vehicleFilter ? ` | Vehicle: ${vehicleFilter}` : ''}
          {driverFilter ? ` | Driver: ${driverFilter}` : ''}
        </p>
      </div>

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 no-print">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Vehicle History</h1>
          <p className="text-sm text-muted mt-1">View all completed trips</p>
        </div>
        <div className="flex gap-2 shrink-0">
          <button
            onClick={() => window.print()}
            disabled={filtered.length === 0}
            className="inline-flex items-center gap-2 px-4 py-2 bg-slate-600 hover:bg-slate-700 text-white rounded-lg font-medium text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed shadow-sm"
          >
            <Printer className="w-4 h-4" />
            Print Report
          </button>
          <button
            onClick={exportToExcel}
            disabled={filtered.length === 0}
            className="inline-flex items-center gap-2 px-4 py-2 bg-success-600 hover:bg-success-700 text-white rounded-lg font-medium text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed shadow-sm"
          >
            <Download className="w-4 h-4" />
            Export to Excel
          </button>
        </div>
      </div>

      {/* Filters */}
      <Card className="no-print">
        <div className="flex flex-wrap items-end gap-3">
          <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-500 uppercase tracking-wider pt-1">
            <Filter className="w-3.5 h-3.5" /> Filters
          </div>

          {/* Employee No. */}
          <div className="flex-1 min-w-[140px] space-y-1">
            <label className="text-xs font-medium text-slate-600">Employee No.</label>
            <input
              type="text"
              placeholder="e.g. EMP005"
              value={empFilter}
              onChange={e => setEmpFilter(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            />
          </div>

          {/* Travel Type */}
          <div className="flex-1 min-w-[160px] space-y-1">
            <label className="text-xs font-medium text-slate-600">Travel Type</label>
            <select
              value={typeFilter}
              onChange={e => setTypeFilter(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            >
              <option value="">All Types</option>
              <option value="Within Anuppur/Shahdol">Within Anuppur/Shahdol</option>
              <option value="Beyond Anuppur/Shahdol">Beyond Anuppur/Shahdol</option>
            </select>
          </div>

          {/* Pickup Date From */}
          <div className="flex-1 min-w-[150px] space-y-1">
            <label className="text-xs font-medium text-slate-600">Pickup Date From</label>
            <input
              type="date"
              value={pickupFrom}
              onChange={e => setPickupFrom(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            />
          </div>

          {/* Pickup Date To */}
          <div className="flex-1 min-w-[150px] space-y-1">
            <label className="text-xs font-medium text-slate-600">Pickup Date To</label>
            <input
              type="date"
              value={pickupTo}
              onChange={e => setPickupTo(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            />
          </div>

          {/* Vehicle */}
          <div className="flex-1 min-w-[160px] space-y-1">
            <label className="text-xs font-medium text-slate-600">Vehicle</label>
            <select
              value={vehicleFilter}
              onChange={e => setVehicleFilter(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            >
              <option value="">All Vehicles</option>
              {uniqueVehicles.map(v => <option key={v} value={v}>{v}</option>)}
            </select>
          </div>

          {/* Driver */}
          <div className="flex-1 min-w-[160px] space-y-1">
            <label className="text-xs font-medium text-slate-600">Driver</label>
            <select
              value={driverFilter}
              onChange={e => setDriverFilter(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            >
              <option value="">All Drivers</option>
              {uniqueDrivers.map(d => <option key={d} value={d}>{d}</option>)}
            </select>
          </div>

          {/* Sort Order */}
          <div className="flex-1 min-w-[160px] space-y-1">
            <label className="text-xs font-medium text-slate-600">Sort Order</label>
            <select
              value={sortOrder}
              onChange={e => setSortOrder(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            >
              <option value="desc">Newest First (Descending)</option>
              <option value="asc">Oldest First (Ascending)</option>
            </select>
          </div>

          {/* Clear */}
          {hasFilters && (
            <button
              onClick={clearFilters}
              className="flex items-center gap-1.5 px-3 py-2 text-xs font-medium text-danger-600 bg-danger-50 hover:bg-danger-100 rounded-lg transition-colors mt-5"
            >
              <X className="w-3.5 h-3.5" /> Clear
            </button>
          )}
        </div>
      </Card>

      {/* Table */}
      <Card noPadding>
        {sorted.length === 0 ? (
          <div className="p-10 text-center">
            <p className="text-sm text-muted">No completed trips match the filters.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border bg-slate-50/50">
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Employee</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Emp. No.</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Type</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Pickup Location</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Destination</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Vehicle</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Driver</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Pickup Time</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Drop-off Time</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {sorted.map(trip => (
                  <tr key={trip.id} className="hover:bg-slate-50/50 transition-colors">
                    <td className="px-6 py-3.5 font-medium text-slate-800">{trip.requester_name}</td>
                    <td className="px-6 py-3.5 text-slate-600 font-mono text-xs">{trip.employee_number}</td>
                    <td className="px-6 py-3.5">
                      <span className={`text-xs px-2 py-0.5 rounded-md font-medium ${
                        trip.travel_type?.includes('Beyond')
                          ? 'bg-warning-50 text-warning-600'
                          : 'bg-primary-50 text-primary-600'
                      }`}>
                        {trip.travel_type}
                      </span>
                    </td>
                    <td className="px-6 py-3.5 text-slate-700">{trip.pickup_location || '—'}</td>
                    <td className="px-6 py-3.5 text-slate-700">{trip.destination}</td>
                    <td className="px-6 py-3.5 text-slate-600">{trip.registration_no} ({trip.vehicle_make} {trip.vehicle_model})</td>
                    <td className="px-6 py-3.5 text-slate-600">{trip.assigned_driver}</td>
                    <td className="px-6 py-3.5 text-slate-600">{trip.pickup_time ? new Date(trip.pickup_time).toLocaleString() : '—'}</td>
                    <td className="px-6 py-3.5 text-slate-600">{new Date(trip.dropoff_time).toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}
