import { useState, useEffect } from 'react';
import api from '../../services/api';
import Card from '../../components/ui/Card';
import Spinner from '../../components/ui/Spinner';
import { ScrollText, ChevronLeft, ChevronRight, Printer } from 'lucide-react';

export default function AuditLogs() {
  const [logs, setLogs] = useState([]);
  const [pagination, setPagination] = useState({ page: 1, pages: 1, total: 0 });
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState({ action: '', entity_type: '' });
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');

  useEffect(() => { fetchLogs(1); }, [filter, fromDate, toDate]);

  async function fetchLogs(page) {
    setLoading(true);
    try {
      const params = new URLSearchParams({ page, limit: 20 });
      if (filter.action) params.set('action', filter.action);
      if (filter.entity_type) params.set('entity_type', filter.entity_type);
      if (fromDate) params.set('from_date', fromDate);
      if (toDate) params.set('to_date', toDate);

      const { data } = await api.get(`/admin/audit-logs?${params}`);
      setLogs(data.logs);
      setPagination(data.pagination);
    } catch (err) { console.error(err); }
    finally { setLoading(false); }
  }

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Printable Report Header */}
      <div className="print-header">
        <h1 className="text-xl font-bold">System Activity Audit Logs Report</h1>
        <p className="text-sm">Generated by: Administrator</p>
        <p className="text-xs text-slate-500">
          Generated on: {new Date().toLocaleString('en-IN')} 
          {filter.action ? ` | Action: ${filter.action}` : ''}
          {filter.entity_type ? ` | Entity: ${filter.entity_type}` : ''}
          {fromDate ? ` | From: ${fromDate}` : ''}
          {toDate ? ` | To: ${toDate}` : ''}
        </p>
      </div>

      <div className="flex items-center justify-between no-print">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Audit Logs</h1>
          <p className="text-sm text-muted mt-1">Complete activity history across the portal</p>
        </div>
        <button
          onClick={() => window.print()}
          className="flex items-center gap-2 px-4 py-2 bg-white border border-border rounded-lg text-sm font-medium text-slate-700 hover:bg-slate-50 shadow-sm"
        >
          <Printer className="w-4 h-4" />
          Print Logs
        </button>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-3 items-center no-print">
        <select
          value={filter.action}
          onChange={e => setFilter(f => ({ ...f, action: e.target.value }))}
          className="px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
        >
          <option value="">All Actions</option>
          {['CREATE_REQUEST', 'CANCEL_REQUEST', 'HOD_APPROVE', 'HOD_REJECT', 'COO_APPROVE', 'COO_REJECT',
            'ASSIGN_VEHICLE', 'RECORD_PICKUP', 'RECORD_DROPOFF', 'CREATE_EMPLOYEE', 'UPDATE_EMPLOYEE', 'DEACTIVATE_EMPLOYEE']
            .map(a => <option key={a} value={a}>{a.replace(/_/g, ' ')}</option>)}
        </select>
        <select
          value={filter.entity_type}
          onChange={e => setFilter(f => ({ ...f, entity_type: e.target.value }))}
          className="px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
        >
          <option value="">All Entities</option>
          <option value="vehicle_request">Vehicle Request</option>
          <option value="employee">Employee</option>
        </select>
        <div className="flex items-center gap-2">
          <span className="text-xs font-medium text-slate-500">From:</span>
          <input
            type="date"
            value={fromDate}
            onChange={e => setFromDate(e.target.value)}
            className="px-3 py-1.5 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
          />
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs font-medium text-slate-500">To:</span>
          <input
            type="date"
            value={toDate}
            onChange={e => setToDate(e.target.value)}
            className="px-3 py-1.5 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
          />
        </div>
      </div>

      <Card noPadding>
        {loading ? <Spinner className="py-10" /> : (
          <>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-border bg-slate-50/50">
                    <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Timestamp</th>
                    <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Actor</th>
                    <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Action</th>
                    <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Entity</th>
                    <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">Details</th>
                    <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase">IP</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {logs.map(log => (
                    <tr key={log.id} className="hover:bg-slate-50/50">
                      <td className="px-6 py-3 text-xs text-slate-500 whitespace-nowrap">{new Date(log.created_at).toLocaleString()}</td>
                      <td className="px-6 py-3 text-slate-700">{log.actor_name || '—'}</td>
                      <td className="px-6 py-3">
                        <span className="px-2 py-0.5 rounded-md bg-slate-100 text-xs font-mono text-slate-600">{log.action}</span>
                      </td>
                      <td className="px-6 py-3 text-slate-600">{log.entity_type} #{log.entity_id}</td>
                      <td className="px-6 py-3 text-xs text-slate-500 max-w-48 truncate">
                        {log.details ? JSON.stringify(typeof log.details === 'string' ? JSON.parse(log.details) : log.details) : '—'}
                      </td>
                      <td className="px-6 py-3 text-xs text-slate-400 font-mono">{log.ip_address || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Pagination */}
            <div className="flex items-center justify-between px-6 py-3 border-t border-border bg-slate-50/50 no-print">
              <span className="text-xs text-muted">
                Showing {(pagination.page - 1) * 20 + 1}–{Math.min(pagination.page * 20, pagination.total)} of {pagination.total}
              </span>
              <div className="flex items-center gap-1">
                <button
                  disabled={pagination.page <= 1}
                  onClick={() => fetchLogs(pagination.page - 1)}
                  className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 disabled:opacity-30"
                >
                  <ChevronLeft className="w-4 h-4" />
                </button>
                <span className="text-xs text-slate-600 px-2">{pagination.page} / {pagination.pages}</span>
                <button
                  disabled={pagination.page >= pagination.pages}
                  onClick={() => fetchLogs(pagination.page + 1)}
                  className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 disabled:opacity-30"
                >
                  <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          </>
        )}
      </Card>
    </div>
  );
}
