import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import api from '../../services/api';
import Card from '../../components/ui/Card';
import StatusBadge from '../../components/ui/StatusBadge';
import Spinner from '../../components/ui/Spinner';
import { History, ExternalLink, Download, Printer } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export default function ApprovalHistory() {
  const { user } = useAuth();
  const [requests, setRequests] = useState([]);
  const [loading, setLoading] = useState(true);

  // Filters
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');
  const [travelType, setTravelType] = useState('');

  useEffect(() => {
    fetchRequests();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [fromDate, toDate, travelType, user]);

  async function fetchRequests() {
    if (!user) return;
    setLoading(true);
    try {
      const params = {};
      if (fromDate) params.from_date = fromDate;
      if (toDate) params.to_date = toDate;
      if (travelType) params.type = travelType;
      
      const endpoint = user.role === 'COO' ? '/approvals/coo/history' : '/approvals/hod/history';
      const { data } = await api.get(endpoint, { params });
      setRequests(data.requests || []);
    } catch (err) {
      console.error('Failed to fetch approval history:', err);
    } finally {
      setLoading(false);
    }
  }

  // Frontend local filtering for now if server doesn't support params yet
  const filteredRequests = requests.filter(req => {
    if (fromDate && new Date(req.created_at) < new Date(fromDate)) return false;
    if (toDate) {
      const nextDay = new Date(toDate);
      nextDay.setDate(nextDay.getDate() + 1);
      if (new Date(req.created_at) >= nextDay) return false;
    }
    if (travelType) {
      if (travelType === 'Within Anuppur/Shahdol' && req.travel_type.includes('Beyond')) return false;
      if (travelType === 'Beyond Anuppur/Shahdol' && !req.travel_type.includes('Beyond')) return false;
    }
    return true;
  });

  const exportToCSV = () => {
    if (filteredRequests.length === 0) return;
    
    const escape = (val) => {
      if (val === null || val === undefined) return '';
      const str = String(val).replace(/"/g, '""');
      return str.includes(',') || str.includes('"') || str.includes('\n') ? `"${str}"` : str;
    };

    const headers = [
      'Request ID', 'Requester Name', 'Requester Email', 'Work Type', 'Destination', 'Pickup Location',
      'Purpose', 'Requested On', 'Travel Date', 'Travel Time', 'Passengers', 
      'Your Action Date', 'Your Remarks', 'Current Status'
    ];

    const rows = filteredRequests.map(req => [
      req.id,
      req.requester_name,
      req.requester_email,
      req.work_type,
      req.destination,
      req.pickup_location,
      req.purpose,
      new Date(req.created_at).toLocaleString('en-IN'),
      req.travel_date,
      req.travel_time,
      req.passengers,
      new Date(user.role === 'COO' ? req.coo_action_at : req.hod_action_at).toLocaleString('en-IN'),
      user.role === 'COO' ? req.coo_remarks || '' : req.hod_remarks || '',
      req.status.replace(/_/g, ' ')
    ].map(escape));

    const BOM = '\uFEFF';
    const csvContent = BOM + [headers.join(','), ...rows.map(r => r.join(','))].join('\r\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${user.role}_Approval_History.csv`;
    link.click();
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Printable Report Header */}
      <div className="print-header">
        <h1 className="text-xl font-bold">{user.role} Approval History Report</h1>
        <p className="text-sm">Generated by: {user.full_name} ({user.email})</p>
        <p className="text-xs text-slate-500">
          Generated on: {new Date().toLocaleString('en-IN')} 
          {fromDate ? ` | From Date: ${fromDate}` : ''}
          {toDate ? ` | To Date: ${toDate}` : ''}
          {travelType ? ` | Travel Type: ${travelType}` : ''}
        </p>
      </div>

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 no-print">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Approval History</h1>
          <p className="text-sm text-muted mt-1">View requests previously processed by you</p>
        </div>
        <div className="flex gap-2 shrink-0">
          <button
            onClick={() => window.print()}
            disabled={filteredRequests.length === 0}
            className="inline-flex items-center gap-2 px-4 py-2 bg-slate-600 hover:bg-slate-700 text-white rounded-lg font-medium text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed shadow-sm"
          >
            <Printer className="w-4 h-4" />
            Print Report
          </button>
          <button
            onClick={exportToCSV}
            disabled={filteredRequests.length === 0}
            className="inline-flex items-center gap-2 px-4 py-2 bg-success-600 hover:bg-success-700 text-white rounded-lg font-medium text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed shadow-sm"
          >
            <Download className="w-4 h-4" />
            Export to Excel
          </button>
        </div>
      </div>

      <Card className="no-print">
        <div className="flex flex-col md:flex-row md:items-end gap-4">
          <div className="flex-1 space-y-1">
            <label className="text-xs font-medium text-slate-700">From Date (Requested On)</label>
            <input
              type="date"
              value={fromDate}
              onChange={e => setFromDate(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            />
          </div>
          <div className="flex-1 space-y-1">
            <label className="text-xs font-medium text-slate-700">To Date (Requested On)</label>
            <input
              type="date"
              value={toDate}
              onChange={e => setToDate(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            />
          </div>
          <div className="flex-1 space-y-1">
            <label className="text-xs font-medium text-slate-700">Travel Type</label>
            <select
              value={travelType}
              onChange={e => setTravelType(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            >
              <option value="">All Types</option>
              <option value="Within Anuppur/Shahdol">Within Anuppur/Shahdol</option>
              <option value="Beyond Anuppur/Shahdol">Beyond Anuppur/Shahdol</option>
            </select>
          </div>
        </div>
      </Card>

      <Card noPadding>
        {loading ? (
          <Spinner size="md" className="py-20" />
        ) : filteredRequests.length === 0 ? (
          <div className="p-10 text-center">
            <History className="w-12 h-12 text-slate-200 mx-auto mb-3" />
            <p className="text-sm text-muted">No processed requests found matching the filters.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border bg-slate-50/50">
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">ID</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Requester</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Destination</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Category</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Requested On</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Travel Date</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Your Action Date</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Your Remarks</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Current Status</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider no-print">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {filteredRequests.map((req, i) => (
                  <tr key={req.id} className="hover:bg-slate-50/50 transition-colors">
                    <td className="px-6 py-3.5 font-mono text-xs text-slate-500">#{req.id}</td>
                    <td className="px-6 py-3.5">
                      <p className="font-medium text-slate-800">{req.requester_name}</p>
                      <p className="text-xs text-muted">{req.requester_email}</p>
                    </td>
                    <td className="px-6 py-3.5 text-slate-700">{req.destination}</td>
                    <td className="px-6 py-3.5">
                      <span className={`text-xs px-2 py-0.5 rounded-md ${req.work_type === 'Personal' ? 'bg-purple-50 text-purple-600' : 'bg-blue-50 text-blue-600'}`}>
                        {req.work_type === 'Personal' ? 'Personal' : 'Company'}
                      </span>
                    </td>
                    <td className="px-6 py-3.5 text-slate-600">{new Date(req.created_at).toLocaleDateString()}</td>
                    <td className="px-6 py-3.5 text-slate-600">{req.travel_date} {req.travel_time}</td>
                    <td className="px-6 py-3.5 text-slate-600">
                      {new Date(user.role === 'COO' ? req.coo_action_at : req.hod_action_at).toLocaleString()}
                    </td>
                    <td className="px-6 py-3.5 text-slate-600 italic max-w-xs truncate" title={user.role === 'COO' ? req.coo_remarks : req.hod_remarks}>
                      {user.role === 'COO' ? req.coo_remarks || '—' : req.hod_remarks || '—'}
                    </td>
                    <td className="px-6 py-3.5"><StatusBadge status={req.status} /></td>
                    <td className="px-6 py-3.5 no-print">
                      <Link to={`/requests/${req.id}`} className="inline-flex items-center gap-1 text-primary-600 hover:text-primary-700 font-medium">
                        View <ExternalLink className="w-3.5 h-3.5" />
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}
