import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import api from '../../services/api';
import Card from '../../components/ui/Card';
import StatusBadge from '../../components/ui/StatusBadge';
import Spinner from '../../components/ui/Spinner';
import { History, ExternalLink, Download, Printer } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export default function RequestHistory() {
  const { user } = useAuth();
  const [requests, setRequests] = useState([]);
  const [loading, setLoading] = useState(true);
  const [sortOrder, setSortOrder] = useState('desc');
  
  // Filters
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');
  const [travelType, setTravelType] = useState('');

  useEffect(() => {
    fetchRequests();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [fromDate, toDate, travelType]);

  const sortedRequests = [...requests].sort((a, b) => {
    const dateA = new Date(a.created_at);
    const dateB = new Date(b.created_at);
    return sortOrder === 'desc' ? dateB - dateA : dateA - dateB;
  });

  async function fetchRequests() {
    setLoading(true);
    try {
      const params = {};
      if (fromDate) params.from_date = fromDate;
      if (toDate) params.to_date = toDate;
      if (travelType) params.type = travelType;
      
      const { data } = await api.get('/requests/my', { params });
      setRequests(data.requests);
    } catch (err) {
      console.error('Failed to fetch requests history:', err);
    } finally {
      setLoading(false);
    }
  }

  const exportToExcel = async () => {
    if (requests.length === 0) return;
    try {
      // Build query params to match current filters
      const params = {};
      if (fromDate) params.from_date = fromDate;
      if (toDate) params.to_date = toDate;
      if (travelType) params.type = travelType;

      // Fetch the CSV from the server using axios (sends auth cookie automatically)
      const response = await api.get('/requests/my/export', {
        params,
        responseType: 'blob', // Receive raw binary data
      });

      // Create a temporary URL from the blob and trigger download
      const blob = new Blob([response.data], { type: 'text/csv;charset=utf-8;' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'Request_History.csv';
      link.click();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      alert('Failed to export. Please try again.');
      console.error(err);
    }
  };


  return (
    <div className="space-y-6 animate-fade-in">
      {/* Printable Report Header */}
      <div className="print-header">
        <h1 className="text-xl font-bold">Employee Request History Report</h1>
        <p className="text-sm">Generated by: {user?.full_name} ({user?.email})</p>
        <p className="text-xs text-slate-500">
          Generated on: {new Date().toLocaleString('en-IN')} 
          {fromDate ? ` | From Date: ${fromDate}` : ''}
          {toDate ? ` | To Date: ${toDate}` : ''}
          {travelType ? ` | Travel Type: ${travelType}` : ''}
        </p>
      </div>

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 no-print">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Request History</h1>
          <p className="text-sm text-muted mt-1">View and filter your past vehicle requests</p>
        </div>
        <div className="flex gap-2 shrink-0">
          <button
            onClick={() => window.print()}
            disabled={requests.length === 0}
            className="inline-flex items-center gap-2 px-4 py-2 bg-slate-600 hover:bg-slate-700 text-white rounded-lg font-medium text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed shadow-sm"
          >
            <Printer className="w-4 h-4" />
            Print Report
          </button>
          <button
            onClick={exportToExcel}
            disabled={requests.length === 0}
            className="inline-flex items-center gap-2 px-4 py-2 bg-success-600 hover:bg-success-700 text-white rounded-lg font-medium text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed shadow-sm"
          >
            <Download className="w-4 h-4" />
            Export to Excel
          </button>
        </div>
      </div>

      <Card className="no-print">
        <div className="flex flex-col md:flex-row md:items-end gap-4">
          <div className="flex-1 space-y-1">
            <label className="text-xs font-medium text-slate-700">From Date (Requested On)</label>
            <input
              type="date"
              value={fromDate}
              onChange={e => setFromDate(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            />
          </div>
          <div className="flex-1 space-y-1">
            <label className="text-xs font-medium text-slate-700">To Date (Requested On)</label>
            <input
              type="date"
              value={toDate}
              onChange={e => setToDate(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            />
          </div>
          <div className="flex-1 space-y-1">
            <label className="text-xs font-medium text-slate-700">Travel Type</label>
            <select
              value={travelType}
              onChange={e => setTravelType(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            >
              <option value="">All Types</option>
              <option value="Within Anuppur/Shahdol">Within Anuppur/Shahdol</option>
              <option value="Beyond Anuppur/Shahdol">Beyond Anuppur/Shahdol</option>
            </select>
          </div>
          <div className="flex-1 space-y-1">
            <label className="text-xs font-medium text-slate-700">Sort Order</label>
            <select
              value={sortOrder}
              onChange={e => setSortOrder(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-white focus:border-primary-500 outline-none"
            >
              <option value="desc">Newest First (Descending)</option>
              <option value="asc">Oldest First (Ascending)</option>
            </select>
          </div>
        </div>
      </Card>

      <Card noPadding>
        {loading ? (
          <Spinner size="md" className="py-20" />
        ) : requests.length === 0 ? (
          <div className="p-10 text-center">
            <History className="w-12 h-12 text-slate-200 mx-auto mb-3" />
            <p className="text-sm text-muted">No requests found matching the filters.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border bg-slate-50/50">
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">ID</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Destination</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Category</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Requested On</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Travel Date</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Type</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Status</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Vehicle</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider no-print">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {sortedRequests.map((req, i) => (
                  <tr key={req.id} className="hover:bg-slate-50/50 transition-colors" style={{ animationDelay: `${(i % 10) * 50}ms` }}>
                    <td className="px-6 py-3.5 font-mono text-xs text-slate-500">#{req.id}</td>
                    <td className="px-6 py-3.5 font-medium text-slate-800">{req.destination}</td>
                    <td className="px-6 py-3.5">
                      <span className={`text-xs px-2 py-0.5 rounded-md ${req.work_type === 'Personal' ? 'bg-purple-50 text-purple-600' : 'bg-blue-50 text-blue-600'}`}>
                        {req.work_type === 'Personal' ? 'Personal' : 'Company'}
                      </span>
                    </td>
                    <td className="px-6 py-3.5 text-slate-600">{new Date(req.created_at).toLocaleDateString()}</td>
                    <td className="px-6 py-3.5 text-slate-600">{req.travel_date}</td>
                    <td className="px-6 py-3.5">
                      <span className={`text-xs px-2 py-0.5 rounded-md ${req.travel_type.includes('Beyond') ? 'bg-warning-50 text-warning-600' : 'bg-primary-50 text-primary-600'}`}>
                        {req.travel_type}
                      </span>
                    </td>
                    <td className="px-6 py-3.5"><StatusBadge status={req.status} /></td>
                    <td className="px-6 py-3.5 text-slate-600">{req.registration_no || '—'}</td>
                    <td className="px-6 py-3.5 no-print">
                      <Link to={`/requests/${req.id}`} className="inline-flex items-center gap-1 text-primary-600 hover:text-primary-700 font-medium">
                        View <ExternalLink className="w-3.5 h-3.5" />
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}
